### ISSUE TITLE
How to reorganize, with keeping history of codes

### ISSUE THREAD

**Issue by ajinkyakolhe112** [pedrovgs/Algorithms#18]
Hi,
I have two questions, and don't know how to contact you except raising issue. :)

1st 
How do I create a repo with all comit history preserved, with all codes in just main and test package. I tried doing that in https://github.com/ajinkyakolhe112/JavaAlgorithms

2nd
I am giving you full credit for the code. So I am allowed to do this right?

Thanks.

**Comment by pedrovgs** [comment]
@ajinkyakolhe112 you have my email at the end of the project README.md.

You should fork the project using GitHub. And keep the attribution to Pedro Vicente Gómez Sánchez, because this project is using Apache v2 as license. You can read the full license if you want :)
