### ISSUE TITLE
Question about problem44 test

### ISSUE THREAD

**Issue by ZephyrJung** [pedrovgs/Algorithms#28]
https://github.com/pedrovgs/Algorithms/blob/master/src/test/java/com/github/pedrovgs/problem44/FindMinNumberAtPositionTest.java#L47

Why it should cause a exception when there is a element in the tree and the position is 1?
it should return the element whose index is position-1, isn't it?
https://github.com/pedrovgs/Algorithms/blob/master/src/main/java/com/github/pedrovgs/problem44/FindMinNumberAtPosition.java#L52
I think this line should be:
```java
if (position > orderedElements.size()) {
```
or you can't get the last element in the tree

**Comment by pedrovgs** [comment]
Hi @ZephyrJung, sorry for the late response. As we start counting by zero if you have a tree with just  1 element and you ask for the item at position 1 the exception is thrown. With a size 1 tree we will have just one position associated with the number 0.
