### ISSUE TITLE
AreAnagrams is wrong

### ISSUE THREAD

**Issue by sm4** [pedrovgs/Algorithms#34]
The Anagrams algorithm is wrong. Consider the following test case:

```
public class AreAnagramsTest {
    @Test
    public void check() throws Exception {
        AreAnagrams areAnagrams = new AreAnagrams();
        assertFalse(areAnagrams.check("abc", "efg"));
    }
}
```

You cannot use sums of the values. You need to compare whether you have enough characters in each array one by one.

**Comment by pedrovgs** [comment]
You are totally right @sm4 Thanks! I've updated the implementation to sort the arrays and compare the values. I've added your test so we can see if the new implementation works.
