### ISSUE TITLE
visibility and initialization

### ISSUE THREAD

**Issue by lprone** [pedrovgs/Algorithms#49]
https://github.com/pedrovgs/Algorithms/blob/7729e8135393710083184ce6ab6a8a1faebd447b/src/main/java/com/github/pedrovgs/problem46/BinaryTreeSerialization.java#L54

This variable could be defined as:
`
  private int index;
`
and placed above the methods

**Comment by lprone** [comment]
https://github.com/pedrovgs/Algorithms/blob/7729e8135393710083184ce6ab6a8a1faebd447b/src/main/java/com/github/pedrovgs/problem37/PathCalculator.java#L30

Here you can define as:
`
private static final String DIR_SEPARATOR = "/";
`

**Comment by pedrovgs** [comment]
Hi @lprone thanks for your suggestions. Could you send a PR with the changes proposed?

**Comment by lprone** [comment]
> Hi @lprone thanks for your suggestions. Could you send a PR with the changes proposed?

Done

**Comment by pedrovgs** [comment]
Great thanks!!
