### ISSUE TITLE
Why don't you have a main?

### ISSUE THREAD

**Issue by hsavit1** [pedrovgs/Algorithms#7]
Disclaimer: noob

When I type javac Trie.java I get this output

> Trie.java:5: error: package com.jwetherell.algorithms.data_structures.interfaces does not exist
import com.jwetherell.algorithms.data_structures.interfaces.ITree

**Comment by hsavit1** [comment]
Ok, Ive realized that you need to execute from the proper folder. sorry for this noobish mistake.

I do have another issue, however. How come there is no Main to run the code from?!

**Comment by pedrovgs** [comment]
I use tests to run my code and check if the software is working or not :)
