### ISSUE TITLE
I am confused about the bubble sort.

### ISSUE THREAD

**Issue by bigscorpions** [pedrovgs/Algorithms#9]
I read your code and I don't think the bubble sort is like what I read from the algorithm books. I don't get it. The comment says 'compares each pair of adjacent items and swaps them if they are in the wrong order'，but it is not. The code is compare the elment to the others every step(not adjacent ones). It works but it is not as the comment says.

**Comment by pedrovgs** [comment]
Hi @bigscorpions feel free to send any PR with your implementation :)

**Comment by pedrovgs** [comment]
Fixed in #10
